##### This file preprocesses the original data file 'Supporting information CSV.csv' distributed under the Creative Commons Attribution 3.0 Unported LICENSE. The content of this file acts as the documentation of modifications and adaptations that are required to be indicated and marked according to the license
###### More information: https://wiki.creativecommons.org/wiki/License_Versions#Modifications_and_adaptations_must_be_marked_as_such

In [123]:
import pandas as pd 
import numpy as np

In [124]:
# Load the original data (Wang et al., 2017)
df = pd.read_csv('Supporting information CSV.csv', skiprows=1, sep=',')
df.head(3)

,ID,MCM_ID,SMILES,structure,MF,MW,PRECURSOR,oxidation genration,C,H,...,R2 (E),ppLFER_logKWIOM/G,ppLFER_logKW/G,SPARC_logKWIOM/G,SPARC_logKW/G,COSMOtherm_logKWIOM/G,COSMOtherm_logKW/G,COSMOtherm vapor pressure (kPa),COSMOtherm activity coefficients in WIOM,COSMOtherm activity coefficient in water
0,1,C918NO3,CC1(C)C(CC1C(=O)CC=O)ON(=O)=O,NaN,C9H13NO5,215.20,BPINENE,2.0,9,13,...,0.84,7.9,7.15,8.21,7.13,8.26,5.13,5.900000e-05,1.02,14600.0
1,2,C134CO,CC(=O)CCC(=O)C(C)(C)C(=O)C(=O)C(=O)CCO,NaN,C13H18O6,270.28,BCARY,3.0,13,18,...,1.23,13.0,16.05,12.57,14.75,11.50,9.71,1.920000e-08,1.80,1380.0
2,3,NBUTACET,CCCCOC(=O)C,NaN,C6H12O2,116.16,NBUTACET,0.0,6,12,...,0.06,3.3,1.69,3.87,1.84,4.49,2.62,4.230000e-01,0.82,760.0

In [125]:
# Convert P_sat to log10 units
df['COSMOtherm vapor pressure (kPa)'] = np.log10(df['COSMOtherm vapor pressure (kPa)'].values)

# Select the needed columns
cols = ['SMILES', 'COSMOtherm vapor pressure (kPa)', 'COSMOtherm_logKWIOM/G', 'COSMOtherm_logKW/G']
df = df[cols]
df.head(2)

,SMILES,COSMOtherm vapor pressure (kPa),COSMOtherm_logKWIOM/G,COSMOtherm_logKW/G
0,CC1(C)C(CC1C(=O)CC=O)ON(=O)=O,-4.229148,8.26,5.13
1,CC(=O)CCC(=O)C(C)(C)C(=O)C(=O)C(=O)CCO,-7.716699,11.50,9.71

In [126]:
# Save the columns to separate data files
col_to_fname= {
    'SMILES': 'smiles.txt',
    'COSMOtherm vapor pressure (kPa)': 'log_p_sat.txt',
    'COSMOtherm_logKWIOM/G' : 'log_kwiomg.txt',
    'COSMOtherm_logKW/G' : 'log_kwg.txt'
}
for col, fname in col_to_fname.items():
    vals = df[col].values
    if col == 'SMILES':
        with open(fname, 'w+') as file:
            for val in vals:
                file.writelines(val + '\n')
    elif col == 'COSMOtherm vapor pressure (kPa)':
        np.savetxt(fname, vals, fmt='%.15f')
    else:
        np.savetxt(fname, vals, fmt='%.2f')

### Summary of modifications and adaptations:
#### - Convert COSMOtherm vapor pressure (kPa) values to log10(kPa) units
#### - Save columns: 'SMILES', 'COSMOtherm vapor pressure (kPa)', 'COSMOtherm_logKWIOM/G', 'COSMOtherm_logKW/G' to files of different format 'smiles.txt', 'log_p_sat.txt', 'log_kwiomg.txt', 'log_kwg.txt' without headers